# site properties and page defaults
title: Architectural AI Reseach Lab
subtitle: AAIRL
description: The AAIRL is revolutionizing Architecture and Urban Design by leveraging the power of computation, artificial intelligence, and collective intelligence, we are creating new design methods that will lead to more sustainable and equitable cities for a better future.
# header: images/AAIRL_Logo.png
# footer: images/Ariel_U_logo2.jpg
url: "https://aairl.com"
header-dark: true
footer-dark: true

# site social media and other links
links:
  email: jonathand@ariel.ac.il
  orcid: 0000-0002-7464-8526
  # google-scholar: ETJoidYAAAAJ
  github: Architectural-Artificial-Intelligence
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_posts
  - scope:
      type: "projects"
    values:
      layout: projects
  - scope:
      type: "products"
    values:
      layout: products
  - scope:
      type: "study"
    values:
      layout: study
collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  products:
    output: true
  projects:
    output: true
  study:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - .history
